# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM

	pod 'Then', '2.7.0'
	pod 'SnapKit', '5.0.1'
	pod 'RxSwift', '6.2.0'
    	pod 'RxCocoa', '6.2.0'
	pod 'RxDataSources', '5.0.0'

  target 'MVVMTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxBlocking', '6.2.0'
    	pod 'RxTest', '6.2.0'
  end

  target 'MVVMUITests' do
    # Pods for testing
	pod 'RxBlocking', '6.2.0'
    	pod 'RxTest', '6.2.0'
  end

end
